/**
 * @Description SsoTokenService is generated by the auto build Tools.
 * @author luyl
 * @time 2021-10-25 21:07:06
 */

package org.web.common.sso.server.service;

import java.util.List;
import java.util.Map;
import java.util.HashMap;
import javax.annotation.Resource;
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Service;
import org.apache.log4j.Logger;
import org.web.common.sso.server.query.QuerySsoToken;
import org.web.common.sso.server.domain.SsoTokenDO;
import org.web.common.sso.server.dao.SsoTokenDAO;
import org.web.base.domain.exception.ServiceException;

@Service("ssoTokenService")
public class SsoTokenService {

	private static Logger logger = Logger.getLogger(SsoTokenService.class);

	@Resource
	private SsoTokenDAO ssoTokenDAO;

	/**
	 * @Decription 根据主键查询记录
	 * @param ssoTokenId
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回唯一记录SsoToken.
	 */
	public SsoTokenDO selectSsoTokenBySsoTokenId ( Long ssoTokenId) throws ServiceException {
		if(ssoTokenId == null){
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		return ssoTokenDAO.selectSsoTokenBySsoTokenId(ssoTokenId);
	}

	/**
	 * @Decription 根据查询条件,返回List.
	 * @param querySsoToken 封装了查询条件对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回一组记录.
	 */
	public List< SsoTokenDO > selectSsoTokenList(QuerySsoToken querySsoToken) throws ServiceException {

		if (querySsoToken == null) {
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		//TODO
		setDefaultQuery(querySsoToken);
		return ssoTokenDAO.selectSsoTokenList( querySsoToken );
	}

	/**
	 * @Decription 根据查询条件,返回map,map中的KEY是表的主键ssoTokenId.
	 * @param querySsoToken 封装了查询条件对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回一组记录，以主键做为KEY的MAP.
	 */
	public Map< Long, SsoTokenDO > selectSsoTokenMapForSsoTokenId(QuerySsoToken querySsoToken) throws ServiceException {

		if (querySsoToken == null) {
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		//TODO
		setDefaultQuery(querySsoToken);
		List< SsoTokenDO >  list = ssoTokenDAO.selectSsoTokenList( querySsoToken );
		Map<  Long, SsoTokenDO > map = new HashMap<>();
		for ( SsoTokenDO ssoTokenDO : list) {
			map.put(ssoTokenDO.getSsoTokenId(), ssoTokenDO);
		}
		return map;
	}


	/**
	 * @Decription 根据查询条件,查询满足条件的记录数.
	 * @param querySsoToken 封装了查询条件对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回查询条件返回的记录总数.
	 */
	public Integer countSsoTokenList(QuerySsoToken querySsoToken) throws ServiceException {
		if (querySsoToken == null) {
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		setDefaultQuery(querySsoToken);
		return ssoTokenDAO.countSsoTokenList( querySsoToken );
	}

	/**
	 * 默认不查询逻辑删除的数据
	 */
	private void setDefaultQuery(QuerySsoToken querySsoToken){
		if (StringUtils.isEmpty(querySsoToken.getIsDelete())) {
			querySsoToken.setIsDelete("NO");
		}
		if (StringUtils.isEmpty(querySsoToken.getOrderByClause())) {
			//querySsoToken.setOrderByClause("  updateDate DESC ");
		}
	}

	/**
	 * @Decription 根据查询条件,返回第一条记录.
	 * @param querySsoToken 封装了查询条件对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回第一条记录.
	 */
	public SsoTokenDO selectOneSsoToken (QuerySsoToken querySsoToken) throws ServiceException {
		querySsoToken.setFirstRecord();
		List<SsoTokenDO> list = ssoTokenDAO.selectSsoTokenList( querySsoToken );
		if(list != null && list.size() > 0){
			return list.get(0);
		}
		return null;
	}

	/**
	 * @Decription 根据查询条件,查询不重复信息.
	 * @param querySsoToken 封装了查询条件对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回不重复信息.
	 */
	public List<String> selectDistinctList(QuerySsoToken querySsoToken)throws ServiceException {
		if(StringUtils.isEmpty(querySsoToken.getIsDelete())){
			querySsoToken.setIsDelete("NO");
		}
		return ssoTokenDAO.selectDistinctList(querySsoToken);
	}


	/**
	 * @Decription 插入一条新记录.
	 * @param ssoTokenDO 封装新增的对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回原始对象，如果用到数据库自增主键，并会自动设置新增主键.
	 */
	public SsoTokenDO insertSsoToken(SsoTokenDO ssoTokenDO)throws ServiceException {
		// check params first.
		checkInsert(ssoTokenDO);

		// TODO add default value.

		ssoTokenDAO.insertSsoToken(ssoTokenDO);
		return ssoTokenDO;
	}

	/**
	 * @Decription 根据主键修改记录.
	 * @param ssoTokenDO 封装修改的对象.
	 * @author luyl
	 * @date 2021-10-25 21:07:06
	 * @return 返回修改记录数.
	 */
	public int updateSsoTokenBySsoTokenId(SsoTokenDO ssoTokenDO)throws ServiceException {
		// check params first.
		checkUpdate(ssoTokenDO);

		return ssoTokenDAO.updateSsoTokenBySsoTokenId(ssoTokenDO);

	}

	/**
	 * According to DB info. check attribute allow empty or not, and check attribute's length is over upper limit of length or not.
	 * and this method is generate by the auto build tool.
	 */
	@SuppressWarnings({"deprecation" })
	private void checkInsert(SsoTokenDO ssoTokenDO) throws ServiceException {
		if( ssoTokenDO == null){
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		else if (ssoTokenDO.getSsoTokenId()==null
				|| (ssoTokenDO.getSsoTokenId()!=null && String.valueOf(ssoTokenDO.getSsoTokenId()).length() > 10)) {
			throw new ServiceException("PARAM_IS_INVALID","SsoTokenId is null or out of range, Upper limit of length is 10");
		}
		else if (StringUtils.isEmpty(ssoTokenDO.getSsoToken())
				|| (StringUtils.isNotEmpty(ssoTokenDO.getSsoToken()) && ssoTokenDO.getSsoToken().length() > 255)) {
			throw new ServiceException("PARAM_IS_INVALID","SsoToken is null or out of range, Upper limit of length is 255");
		}
		else if (StringUtils.isEmpty(ssoTokenDO.getAccountNum())
				|| (StringUtils.isNotEmpty(ssoTokenDO.getAccountNum()) && ssoTokenDO.getAccountNum().length() > 11)) {
			throw new ServiceException("PARAM_IS_INVALID","AccountNum is null or out of range, Upper limit of length is 11");
		}
		else if (StringUtils.isEmpty(ssoTokenDO.getAccountName())
				|| (StringUtils.isNotEmpty(ssoTokenDO.getAccountName()) && ssoTokenDO.getAccountName().length() > 11)) {
			throw new ServiceException("PARAM_IS_INVALID","AccountName is null or out of range, Upper limit of length is 11");
		}
		else if (ssoTokenDO.getExpireTime()==null
				|| (ssoTokenDO.getExpireTime()!=null && String.valueOf(ssoTokenDO.getExpireTime()).length() > 10)) {
			throw new ServiceException("PARAM_IS_INVALID","ExpireTime is null or out of range, Upper limit of length is 10");
		}
		else if (StringUtils.isEmpty(ssoTokenDO.getIsDelete())
				|| (StringUtils.isNotEmpty(ssoTokenDO.getIsDelete()) && ssoTokenDO.getIsDelete().length() > 255)) {
			throw new ServiceException("PARAM_IS_INVALID","IsDelete is null or out of range, Upper limit of length is 255");
		}

	}

	@SuppressWarnings({"deprecation" })
	private void checkUpdate(SsoTokenDO ssoTokenDO) throws ServiceException {
		if( ssoTokenDO == null){
			throw new ServiceException("PARAM_IS_EMPTY","Query is null.");
		}
		else if (ssoTokenDO.getSsoTokenId()!=null && String.valueOf(ssoTokenDO.getSsoTokenId()).length() > 10) {
			throw new ServiceException("UPDATE_ERROR","SsoTokenId is out of range, Upper limit of length is 10");
		}
		else if (StringUtils.isNotEmpty(ssoTokenDO.getSsoToken()) && ssoTokenDO.getSsoToken().length() > 255) {
			throw new ServiceException("UPDATE_ERROR","SsoToken is out of range, Upper limit of length is 255");
		}
		else if (StringUtils.isNotEmpty(ssoTokenDO.getAccountNum()) && ssoTokenDO.getAccountNum().length() > 11) {
			throw new ServiceException("UPDATE_ERROR","AccountNum is out of range, Upper limit of length is 11");
		}
		else if (StringUtils.isNotEmpty(ssoTokenDO.getAccountName()) && ssoTokenDO.getAccountName().length() > 11) {
			throw new ServiceException("UPDATE_ERROR","AccountName is out of range, Upper limit of length is 11");
		}
		else if (ssoTokenDO.getExpireTime()!=null && String.valueOf(ssoTokenDO.getExpireTime()).length() > 10) {
			throw new ServiceException("UPDATE_ERROR","ExpireTime is out of range, Upper limit of length is 10");
		}
		else if (StringUtils.isNotEmpty(ssoTokenDO.getIsDelete()) && ssoTokenDO.getIsDelete().length() > 255) {
			throw new ServiceException("UPDATE_ERROR","IsDelete is out of range, Upper limit of length is 255");
		}
	}
}



