/**
 * SsoTokenDO entity encapsulation table sso_token record.
 *
 * @author LUYL, Generated by the auto build tools .
 * @Time 2021-10-19 17:33:33
 */
package org.web.sso.common.server.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class SsoTokenDO {

    // access_token表主键
    private Long ssoTokenId;
    // UUID,产生临时token
    private String ssoToken;
    // 登录用户ID
    private String accountNum;
    // 登录用户名
    private String accountName;
    // token失效时间，单位秒，最少60秒。
    private Long expireTime;
    // 记录修改时间
    private Date updateTime;
    // 记录创建时间
    private Date createTime;
    // N表示未逻辑删除，Y表示逻辑删除
    private String isDelete;

}