/**
 * AccessTokenDO entity encapsulation table access_token record.
 * @author LUYL,Generated by the auto build tools .
 * @Time 2021-10-11 16:57:08
 */
package org.web.common.sso.domain;

import java.util.Date;

import lombok.Getter;
import lombok.Setter;

@Setter
@Getter
public class AccessTokenDO {

	// access_token表主键
	private Long accessTokenId;
	// 三方应用表主键
	private Long appId;
	// 用户ID
	private Long userId;
	// UUID,产生临时token
	private String accessToken;
	// token失效时间，单位秒，最少60秒。
	private Long expireTime;
	// 记录修改时间
	private Date updateTime;
	// 记录创建时间
	private Date createTime;
	// N表示未逻辑删除，Y表示逻辑删除
	private String isDelete;

}


